/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "nodo_comunicacion.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include "ros/ros.h" //Line add by Diego.

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

char **var_env; //Line add by Diego.
static void
nodo_comunicacion_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		DATOS locomotionforwardrqstandrcv_1_arg;
		DATOS locomotionrotaterqstandrcv_1_arg;
		char stopaction_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case locomotionForwardRqstAndRcv:
		_xdr_argument = (xdrproc_t) xdr_DATOS;
		_xdr_result = (xdrproc_t) xdr_RESULTADO;
		local = (char *(*)(char *, struct svc_req *)) locomotionforwardrqstandrcv_1_svc;
		break;

	case locomotionRotateRqstAndRcv:
		_xdr_argument = (xdrproc_t) xdr_DATOS;
		_xdr_result = (xdrproc_t) xdr_RESULTADO;
		local = (char *(*)(char *, struct svc_req *)) locomotionrotaterqstandrcv_1_svc;
		break;

	case checkBumperSemsorState:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) checkbumpersemsorstate_1_svc;
		break;

	case readBateryLevel:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_float;
		local = (char *(*)(char *, struct svc_req *)) readbaterylevel_1_svc;
		break;

	case checkChargin:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) checkchargin_1_svc;
		break;

	case autodocking:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) autodocking_1_svc;
		break;

	case takePicture:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) takepicture_1_svc;
		break;

	case checkPosition:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_RESULTADO;
		local = (char *(*)(char *, struct svc_req *)) checkposition_1_svc;
		break;

	case restartDockServer:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) restartdockserver_1_svc;
		break;

	case stopAutodock:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) stopautodock_1_svc;
		break;

	case stopAction:
		_xdr_argument = (xdrproc_t) xdr_char;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) stopaction_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv, char **envp) //Line Changed by Diego.
{
	register SVCXPRT *transp;

	pmap_unset (NODO_COMUNICACION, NODO_COMUNICACIONVERS);

	transp = svcudp_create(RPC_ANYSOCK);

    /******Iniciacion de ROS************/
	ros::init(argc, argv,"Comunication_node");
	printf("\n*****ROS_SERVER Running******\n");
    var_env=envp;
	/***********************************/

	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, NODO_COMUNICACION, NODO_COMUNICACIONVERS, nodo_comunicacion_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (NODO_COMUNICACION, NODO_COMUNICACIONVERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, NODO_COMUNICACION, NODO_COMUNICACIONVERS, nodo_comunicacion_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (NODO_COMUNICACION, NODO_COMUNICACIONVERS, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
