/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "nodo_comunicacion.h"

RESULTADO *
locomotionforwardrqstandrcv_1_svc(DATOS *argp, struct svc_req *rqstp)
{
	static RESULTADO  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RESULTADO *
locomotionrotaterqstandrcv_1_svc(DATOS *argp, struct svc_req *rqstp)
{
	static RESULTADO  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
checkbumpersemsorstate_1_svc(void *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

float *
readbaterylevel_1_svc(void *argp, struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
checkchargin_1_svc(void *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
autodocking_1_svc(void *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
takepicture_1_svc(void *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RESULTADO *
checkposition_1_svc(void *argp, struct svc_req *rqstp)
{
	static RESULTADO  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
restartdockserver_1_svc(void *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
stopautodock_1_svc(void *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
stopaction_1_svc(char *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}
