/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _NODO_COMUNICACION_H_RPCGEN
#define _NODO_COMUNICACION_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct DATOS {
	float vel_linear;
	float vel_angular;
	float angulo_rotacion;
	float avance;
};
typedef struct DATOS DATOS;

struct RESULTADO {
	float pos_actual_x;
	float pos_actual_y;
	float orientacion_actual;
	int error;
};
typedef struct RESULTADO RESULTADO;

#define NODO_COMUNICACION 0x20000011
#define NODO_COMUNICACIONVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define locomotionForwardRqstAndRcv 1
extern  RESULTADO * locomotionforwardrqstandrcv_1(DATOS *, CLIENT *);
extern  RESULTADO * locomotionforwardrqstandrcv_1_svc(DATOS *, struct svc_req *);
#define locomotionRotateRqstAndRcv 2
extern  RESULTADO * locomotionrotaterqstandrcv_1(DATOS *, CLIENT *);
extern  RESULTADO * locomotionrotaterqstandrcv_1_svc(DATOS *, struct svc_req *);
#define checkBumperSemsorState 3
extern  int * checkbumpersemsorstate_1(void *, CLIENT *);
extern  int * checkbumpersemsorstate_1_svc(void *, struct svc_req *);
#define readBateryLevel 4
extern  float * readbaterylevel_1(void *, CLIENT *);
extern  float * readbaterylevel_1_svc(void *, struct svc_req *);
#define checkChargin 5
extern  int * checkchargin_1(void *, CLIENT *);
extern  int * checkchargin_1_svc(void *, struct svc_req *);
#define autodocking 6
extern  int * autodocking_1(void *, CLIENT *);
extern  int * autodocking_1_svc(void *, struct svc_req *);
#define takePicture 7
extern  int * takepicture_1(void *, CLIENT *);
extern  int * takepicture_1_svc(void *, struct svc_req *);
#define checkPosition 8
extern  RESULTADO * checkposition_1(void *, CLIENT *);
extern  RESULTADO * checkposition_1_svc(void *, struct svc_req *);
#define restartDockServer 9
extern  int * restartdockserver_1(void *, CLIENT *);
extern  int * restartdockserver_1_svc(void *, struct svc_req *);
#define stopAutodock 10
extern  int * stopautodock_1(void *, CLIENT *);
extern  int * stopautodock_1_svc(void *, struct svc_req *);
#define stopAction 11
extern  int * stopaction_1(char *, CLIENT *);
extern  int * stopaction_1_svc(char *, struct svc_req *);
extern int nodo_comunicacion_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define locomotionForwardRqstAndRcv 1
extern  RESULTADO * locomotionforwardrqstandrcv_1();
extern  RESULTADO * locomotionforwardrqstandrcv_1_svc();
#define locomotionRotateRqstAndRcv 2
extern  RESULTADO * locomotionrotaterqstandrcv_1();
extern  RESULTADO * locomotionrotaterqstandrcv_1_svc();
#define checkBumperSemsorState 3
extern  int * checkbumpersemsorstate_1();
extern  int * checkbumpersemsorstate_1_svc();
#define readBateryLevel 4
extern  float * readbaterylevel_1();
extern  float * readbaterylevel_1_svc();
#define checkChargin 5
extern  int * checkchargin_1();
extern  int * checkchargin_1_svc();
#define autodocking 6
extern  int * autodocking_1();
extern  int * autodocking_1_svc();
#define takePicture 7
extern  int * takepicture_1();
extern  int * takepicture_1_svc();
#define checkPosition 8
extern  RESULTADO * checkposition_1();
extern  RESULTADO * checkposition_1_svc();
#define restartDockServer 9
extern  int * restartdockserver_1();
extern  int * restartdockserver_1_svc();
#define stopAutodock 10
extern  int * stopautodock_1();
extern  int * stopautodock_1_svc();
#define stopAction 11
extern  int * stopaction_1();
extern  int * stopaction_1_svc();
extern int nodo_comunicacion_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_DATOS (XDR *, DATOS*);
extern  bool_t xdr_RESULTADO (XDR *, RESULTADO*);

#else /* K&R C */
extern bool_t xdr_DATOS ();
extern bool_t xdr_RESULTADO ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_NODO_COMUNICACION_H_RPCGEN */
