/*
*   Header File for Comunication node server.
*   This code was generated by Diego López Pajares
*   Date: 26/10/2015
*/


//Header Files that needs nodo_comunicacion_server
#include "nodo_comunicacion.h"
#include "ros/ros.h"
#include <geometry_msgs/Twist.h>
#include <kobuki_msgs/BumperEvent.h>
#include <kobuki_msgs/SensorState.h>
#include <tf/transform_broadcaster.h>
#include <nav_msgs/Odometry.h>
#include <diagnostic_msgs/DiagnosticStatus.h>
#include <diagnostic_msgs/DiagnosticArray.h>
#include <math.h>
#include <opencv2/highgui/highgui.hpp>
#include <cv_bridge/cv_bridge.h>
#include <image_transport/image_transport.h>
#include <std_srvs/Empty.h>
#include <nodo_comunicacion/Autodock.h>

#include <actionlib_msgs/GoalID.h>
/*************************DEFINITIONS*********************************/
#define PI 3.141592
#define DEBUG 1
