/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "arduino_comunicacion.h"


void
arduino_comunicacion_1(char *host)
{
	CLIENT *clnt;
	char * *result_1;
	ARDSENSOR  leersensor_1_arg;
	bool_t  *result_2;
	PTUPOS  moveptu_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, ARDUINO_COMUNICACION, ARDUINO_COMUNICACIONVERS, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	//result_1 = leersensor_1(&leersensor_1_arg, clnt);
	//if (result_1 == (char **) NULL) {
		//clnt_perror (clnt, "call failed");
	//}
	moveptu_1_arg.pitch=90;
	moveptu_1_arg.yaw=90;
	printf("%d, %d\n",moveptu_1_arg.pitch,moveptu_1_arg.yaw);
	result_2 = moveptu_1(&moveptu_1_arg, clnt);
	if (result_2 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	arduino_comunicacion_1 (host);
exit (0);
}
