/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "arduino_comunicacion.h"

bool_t
xdr_ARDSENSOR (XDR *xdrs, ARDSENSOR *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->MACplaca, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->IDsensor))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_PTUPOS (XDR *xdrs, PTUPOS *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->yaw))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->pitch))
		 return FALSE;
	return TRUE;
}
