/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "arduino_comunicacion.h"
#include "pantilt/pantilt.h"

// PanTilt 
pantilt ptu(B9600);

char **
leersensor_1_svc(ARDSENSOR *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */

	return &result;
}

bool_t *
moveptu_1_svc(PTUPOS *argp, struct svc_req *rqstp)
{
	static bool_t  result;

	 result = ptu.position(argp->yaw, argp->pitch);

	return &result;
}
