/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ARDUINO_COMUNICACION_H_RPCGEN
#define _ARDUINO_COMUNICACION_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct ARDSENSOR {
	char *MACplaca;
	int IDsensor;
};
typedef struct ARDSENSOR ARDSENSOR;

struct PTUPOS {
	int yaw;
	int pitch;
};
typedef struct PTUPOS PTUPOS;

#define ARDUINO_COMUNICACION 0x30000005
#define ARDUINO_COMUNICACIONVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define leerSensor 1
extern  char ** leersensor_1(ARDSENSOR *, CLIENT *);
extern  char ** leersensor_1_svc(ARDSENSOR *, struct svc_req *);
#define movePTU 2
extern  bool_t * moveptu_1(PTUPOS *, CLIENT *);
extern  bool_t * moveptu_1_svc(PTUPOS *, struct svc_req *);
extern int arduino_comunicacion_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define leerSensor 1
extern  char ** leersensor_1();
extern  char ** leersensor_1_svc();
#define movePTU 2
extern  bool_t * moveptu_1();
extern  bool_t * moveptu_1_svc();
extern int arduino_comunicacion_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_ARDSENSOR (XDR *, ARDSENSOR*);
extern  bool_t xdr_PTUPOS (XDR *, PTUPOS*);

#else /* K&R C */
extern bool_t xdr_ARDSENSOR ();
extern bool_t xdr_PTUPOS ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ARDUINO_COMUNICACION_H_RPCGEN */
